// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model_user_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

MLMApiModelUser _$MLMApiModelUserFromJson(Map<String, dynamic> json) =>
    MLMApiModelUser(
      id: json['id'] as String?,
      dateEntered: json['date_entered'] == null
          ? null
          : DateTime.parse(json['date_entered'] as String),
      dateModified: json['date_modified'] == null
          ? null
          : DateTime.parse(json['date_modified'] as String),
      pan: json['pan'] as String?,
      pin: (json['pin'] as num?)?.toInt(),
      email: json['email'] as String?,
      firstName: json['first_name'] as String?,
      middleName: json['middle_name'] as String?,
      lastName: json['last_name'] as String?,
      cardholderName: json['cardholder_name'] as String?,
      birthday: json['birthday'] == null
          ? null
          : DateTime.parse(json['birthday'] as String),
      sex: json['sex'] as String?,
      address: json['address'] as String?,
      houseNumber: json['house_number'] as String?,
      city: json['city'] as String?,
      zipCode: (json['zip_code'] as num?)?.toInt(),
      oib: json['oib'] as String?,
      idcardNumber: json['idcard_number'] as String?,
      expires: json['expires'] == null
          ? null
          : DateTime.parse(json['expires'] as String),
      mobilePhone: json['mobile_phone'] as String?,
      fixPhone: json['fix_phone'] as String?,
      moneySpent: json['money_spent'] as String?,
      totalDiscount: json['total_discount'] as String?,
      totalTransactions: (json['total_transactions'] as num?)?.toInt(),
      fuelLiterInThisMonth: json['fuel_liter_in_this_month'] as String?,
      familyMembersCount: (json['family_members_count'] as num?)?.toInt(),
      childrenCount: (json['children_count'] as num?)?.toInt(),
      qualification: json['qualification'] as String?,
      extSuglasnost: json['ext_suglasnost'] as String?,
      extSuglasnost2: (json['ext_suglasnost2'] as num?)?.toInt(),
      registered: (json['registered'] as num?)?.toInt(),
      registrationNumber: json['registration_number'] as String?,
      company: (json['company'] as num?)?.toInt(),
      companyName: json['company_name'] as String?,
      hash: json['hash'] as String?,
      favoriteShop: (json['favorite_shop'] as num?)?.toInt(),
      loyaltyStatus: json['loyalty_status'] as String?,
      loyaltyStatusOld: json['loyalty_status_old'] as String?,
      custDiscGroup: json['cust_disc_group'] as String?,
      loyaltyStatusInternal: json['loyalty_status_internal'] as String?,
      wasUser: json['was_user'] as String?,
      dateSmartphone: json['date_smartphone'] == null
          ? null
          : DateTime.parse(json['date_smartphone'] as String),
      parentId: json['parent_id'] as String?,
      externalId: json['external_id'] as String?,
      barcode: json['barcode'] as String?,
      unreadMessages: (json['unread_messages'] as num?)?.toInt(),
      unreadCoupons: (json['unread_coupons'] as num?)?.toInt(),
      unreadActionsStamps: (json['unread_actions_stamps'] as num?)?.toInt(),
      unreadActionsRewards: (json['unread_actions_rewards'] as num?)?.toInt(),
      unreadActionsPoints: (json['unread_actions_points'] as num?)?.toInt(),
      unreadOffers: (json['unread_offers'] as num?)?.toInt(),
      bodovi: json['bodovi'] as String?,
      marketing: (json['marketing'] as num?)?.toInt(),
      notificationPhone: (json['notification_phone'] as num?)?.toInt(),
      notificationEmail: (json['notification_email'] as num?)?.toInt(),
      notificationPost: (json['notification_post'] as num?)?.toInt(),
      notificationSms: (json['notification_sms'] as num?)?.toInt(),
      notificationMessage: (json['notification_message'] as num?)?.toInt(),
      sendPlasticCard: (json['send_plastic_card'] as num?)?.toInt(),
      deviceId: json['device_id'] as String?,
      devicePn: json['device_pn'] as String?,
      pension: json['pension'] as String?,
      familyStatus: json['family_status'] as String?,
      workingStatus: json['working_status'] as String?,
      pets: json['pets'] as String?,
      onlineShopping: json['online_shopping'] as String?,
      status: (json['status'] as num?)?.toInt(),
      childData: (json['child_data'] as List<dynamic>?)
          ?.map((e) => MLMApiModelUser.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$MLMApiModelUserToJson(MLMApiModelUser instance) =>
    <String, dynamic>{
      'id': instance.id,
      'date_entered': instance.dateEntered?.toIso8601String(),
      'date_modified': instance.dateModified?.toIso8601String(),
      'pan': instance.pan,
      'pin': instance.pin,
      'email': instance.email,
      'first_name': instance.firstName,
      'middle_name': instance.middleName,
      'last_name': instance.lastName,
      'cardholder_name': instance.cardholderName,
      'birthday': instance.birthday?.toIso8601String(),
      'sex': instance.sex,
      'address': instance.address,
      'house_number': instance.houseNumber,
      'city': instance.city,
      'zip_code': instance.zipCode,
      'oib': instance.oib,
      'idcard_number': instance.idcardNumber,
      'expires': instance.expires?.toIso8601String(),
      'mobile_phone': instance.mobilePhone,
      'fix_phone': instance.fixPhone,
      'money_spent': instance.moneySpent,
      'total_discount': instance.totalDiscount,
      'total_transactions': instance.totalTransactions,
      'fuel_liter_in_this_month': instance.fuelLiterInThisMonth,
      'family_members_count': instance.familyMembersCount,
      'children_count': instance.childrenCount,
      'qualification': instance.qualification,
      'ext_suglasnost': instance.extSuglasnost,
      'ext_suglasnost2': instance.extSuglasnost2,
      'registered': instance.registered,
      'registration_number': instance.registrationNumber,
      'company': instance.company,
      'company_name': instance.companyName,
      'hash': instance.hash,
      'favorite_shop': instance.favoriteShop,
      'loyalty_status': instance.loyaltyStatus,
      'loyalty_status_old': instance.loyaltyStatusOld,
      'cust_disc_group': instance.custDiscGroup,
      'loyalty_status_internal': instance.loyaltyStatusInternal,
      'was_user': instance.wasUser,
      'date_smartphone': instance.dateSmartphone?.toIso8601String(),
      'parent_id': instance.parentId,
      'external_id': instance.externalId,
      'barcode': instance.barcode,
      'unread_messages': instance.unreadMessages,
      'unread_coupons': instance.unreadCoupons,
      'unread_actions_stamps': instance.unreadActionsStamps,
      'unread_actions_rewards': instance.unreadActionsRewards,
      'unread_actions_points': instance.unreadActionsPoints,
      'unread_offers': instance.unreadOffers,
      'bodovi': instance.bodovi,
      'marketing': instance.marketing,
      'notification_phone': instance.notificationPhone,
      'notification_email': instance.notificationEmail,
      'notification_post': instance.notificationPost,
      'notification_sms': instance.notificationSms,
      'notification_message': instance.notificationMessage,
      'send_plastic_card': instance.sendPlasticCard,
      'device_id': instance.deviceId,
      'device_pn': instance.devicePn,
      'pension': instance.pension,
      'family_status': instance.familyStatus,
      'working_status': instance.workingStatus,
      'pets': instance.pets,
      'online_shopping': instance.onlineShopping,
      'status': instance.status,
      'child_data': instance.childData,
    };
